services:
  sumo_coders.user.controller.index:
    class: SumoCoders\FrameworkUserBundle\Controller\IndexController
    arguments:
      - "@multi_user.base_user.repository"

  sumo_coders.user.controller.add_user:
    class: SumoCoders\FrameworkMultiUserBundle\Controller\UserController
    arguments:
      - "@form.factory"
      - "@router"
      - "@session.flash_bag"
      - "@translator"
      - "SumoCoders\\FrameworkUserBundle\\Form\\AddUserType"
      - "@multi_user.handler.create_user"
      - "@sumo_coders.user.repository.user"
      - "@framework.breadcrumb_builder"
      -
        - {"route": "", "label": "Home"}
        - {"route": "sumocoders_frameworkuser_index_index", "label": "user.header.index"}
        - {"route": "", "label": "user.header.add_user"}
      - "sumocoders_frameworkuser_index_index"

  sumo_coders.user.controller.edit_user:
    class: SumoCoders\FrameworkUserBundle\Controller\EditController
    arguments:
      - "@security.authorization_checker"
      - "@security.token_storage"
      - "@form.factory"
      - "@router"
      - "@session.flash_bag"
      - "@translator"
      - "SumoCoders\\FrameworkUserBundle\\Form\\EditUserType"
      - "@multi_user.handler.update_user"
      - "@sumo_coders.user.repository.user"
      - "@framework.breadcrumb_builder"
      -
        - {"route": "", "label": "Home"}
        - {"route": "sumocoders_frameworkuser_index_index", "label": "user.header.index"}
        - {"route": "", "label": "user.header.edit_user"}
      - "sumocoders_frameworkuser_index_index"

  sumo_coders.user.controller.block:
    class: SumoCoders\FrameworkMultiUserBundle\Controller\BlockController
    arguments:
      - "@multi_user.base_user.repository"
      - "@session.flash_bag"
      - "@translator"
      - "@router"
      - "sumocoders_frameworkuser_index_index"

  sumo_coders.user.controller.delete:
    class: SumoCoders\FrameworkMultiUserBundle\Controller\DeleteController
    arguments:
      - "@form.factory"
      - "@multi_user.handler.delete_user"
      - "@session.flash_bag"
      - "@translator"
      - "@router"
      - "sumocoders_frameworkuser_index_index"
