services:
  sumo_coders.user.repository.user:
    class: SumoCoders\FrameworkUserBundle\Repository\UserRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - SumoCodersFrameworkUserBundle:User
