sumo_coders.user.route.add_user:
  defaults: { _controller: sumo_coders.user.controller.add_user:baseAction }
  path: /user/add-user

sumo_coders.user.route.edit_user:
  defaults: { _controller: sumo_coders.user.controller.edit_user:editAction }
  path: /user/{id}/edit-user

sumo_coders.user.route.block:
  defaults: { _controller: sumo_coders.user.controller.block:toggleAction }
  path: /user/{id}/block

sumo_coders.user.route.delete:
  defaults: { _controller: sumo_coders.user.controller.delete:deleteAction }
  path: /user/{id}/delete
