_tests:
    resource: "@SumoCodersFrameworkCoreBundle/Resources/config/routing_test.yml"
    prefix:   /_tests

_main:
    resource: routing.yml

sumo_coders_example_bundle:
  resource: "@SumoCodersFrameworkExampleBundle/Resources/config/routing.yml"
  prefix: /example
